name: Integration Tests

on:
  schedule:
    # scheduled at 3PM and 3AM daily
    - cron: '0 3,15 * * *'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  run-integration-tests:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    env:
      RUSTC_WRAPPER: /home/runner/.cargo/bin/sccache
      CARGO_INCREMENTAL: 0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Get Pyrsia Cargo.toml for Rust Version
        run: wget https://raw.githubusercontent.com/pyrsia/pyrsia/main/Cargo.toml

      - uses: pyrsia/rust-toolchain@v2

      # Use sscache store in GitHub cache
      - uses: actions/cache@v3
        with:
          path: /home/runner/.cache/sccache
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Install sccache from binary
      - run: |
          .github/workflows/sccache-linux.sh
          sccache --start-server
          sccache --show-stats

      - name: Execute Test Cases
        run: |
          REPO_DIR="./" CLEAN_UP_TEST_ENVIRONMENT=true ./bats/lib/bats/bin/bats ./bats/tests
